### ISSUE TITLE
Loading of challange data files out of the box

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-controller#89]
### Problem description

I made it past the download of challange data by temporarily using my personal account. After downloading the data I get the following error messages while downloading data . 

#### Steps to reproduce the issue

```
$ python scripts/push_challenge_data.py
Welcome, George Kowalski!

dataset: {'name': 'datasets/2014-i2b2-20201203'}
fhir_store: {'name': 'datasets/2014-i2b2-20201203/fhirStores/evaluation'}
annotation_store: {'name': 'datasets/2014-i2b2-20201203/annotationStores/goldstandard'}
patient: {'name': 'datasets/2014-i2b2-20201203/fhirStores/evaluation/fhir/Patient/110'}
Traceback (most recent call last):
  File "scripts/push_challenge_data.py", line 43, in get_or_create_resource
    resource = get_func(*args)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 764, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api/note_api.py", line 402, in __get_note
    return self.call_with_http_info(**kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 842, in call_with_http_info
    collection_formats=params['collection_format'])
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 412, in call_api
    _check_type)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 203, in __call_api
    raise e
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 200, in __call_api
    _request_timeout=_request_timeout)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 436, in request
    headers=headers)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/rest.py", line 240, in GET
    query_params=query_params)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/rest.py", line 225, in request
    raise NotFoundException(http_resp=r)
datanode.exceptions.NotFoundException: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '71'})
HTTP response body: {
  "status": 404,
  "title": "The specified resource was not found"
}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/push_challenge_data.py", line 150, in <module>
    note_create_request=note
  File "scripts/push_challenge_data.py", line 50, in get_or_create_resource
    **kwargs
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 764, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api/note_api.py", line 122, in __create_note
    return self.call_with_http_info(**kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 811, in call_with_http_info
    self.__validate_inputs(kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 711, in __validate_inputs
    configuration=self.api_client.configuration
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1403, in validate_and_convert_types
    check_type=_check_type
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1284, in attempt_convert_item
    configuration, spec_property_naming)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1564, in wrapped_init
    return fn(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'note_type'
```

#### Expected behavior

Program to completely load the challange data set.

**Comment by gkowalski** [comment]
I get the same error with the small data set loading

```
$ python scripts/push_small_dataset.py
Welcome, George Kowalski!

dataset: {'name': 'datasets/2014-i2b2-20201203-subset'}
fhir_store: {'name': 'datasets/2014-i2b2-20201203-subset/fhirStores/evaluation'}
annotation_store: {'name': 'datasets/2014-i2b2-20201203-subset/annotationStores/goldstandard'}
patient: 110
Traceback (most recent call last):
  File "scripts/push_small_dataset.py", line 44, in get_or_create_resource
    resource = get_func(*args)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 764, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api/note_api.py", line 402, in __get_note
    return self.call_with_http_info(**kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 842, in call_with_http_info
    collection_formats=params['collection_format'])
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 412, in call_api
    _check_type)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 203, in __call_api
    raise e
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 200, in __call_api
    _request_timeout=_request_timeout)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 436, in request
    headers=headers)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/rest.py", line 240, in GET
    query_params=query_params)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/rest.py", line 225, in request
    raise NotFoundException(http_resp=r)
datanode.exceptions.NotFoundException: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '71'})
HTTP response body: {
  "status": 404,
  "title": "The specified resource was not found"
}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/push_small_dataset.py", line 157, in <module>
    note_create_request=note
  File "scripts/push_small_dataset.py", line 51, in get_or_create_resource
    **kwargs
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 764, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api/note_api.py", line 122, in __create_note
    return self.call_with_http_info(**kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 811, in call_with_http_info
    self.__validate_inputs(kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 711, in __validate_inputs
    configuration=self.api_client.configuration
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1403, in validate_and_convert_types
    check_type=_check_type
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1284, in attempt_convert_item
    configuration, spec_property_naming)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1564, in wrapped_init
    return fn(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'note_type'
```

**Comment by thomasyu888** [comment]
@gkowalski Please make sure you have the most up to date data-node and client installed.  I just ran the code locally and it was able to run.

**Comment by thomasyu888** [comment]
Closing because this isn't the example load script sites should be running.
